### PR TITLE
Added image, author info, and two talks

### PR DESCRIPTION
**Pull request by tel**
Still need to title and describe the two talks.

### CODE REVIEW

**Comment by jdegoes** [comment]
:+1:  Thanks!

**Comment by jdegoes** [comment]
Oops, conflicts, can you merge against head?

**Comment by tel** [comment]
There we are

**Comment by tel** [comment]
Ah, crap. Yup.

**Comment by tel** [comment]
Oops! Wrong button!

**Comment by jdegoes** [comment]
Thanks!

**Pull request merged**
