### PR TITLE
Behold, I come like a developer in the night...

### PR DESCRIPTION
**Pull request by djspiewak**
Added myself to `index.html`.  Also my editor appears to have cleaned up your whitespace problem.  You're welcome.

### CODE REVIEW

**Comment by jdegoes** [comment]
:+1:

**Comment by jdegoes** [comment]
@djspiewak Oops, can you add the talk title & description, too? Forgot to check for that. Thanks!

**Comment by djspiewak** [comment]
@jdegoes I left it off since it's in a schedule format, and I didn't want to just arbitrarily plop my talk into a particular time slot.  I can just add it at the end or something if you would like.  (in other news, the speakers also appeared to be in a very haphazard order; wasn't sure what to do with that)

**Comment by jdegoes** [comment]
Currently the talks are not scheduled and everything's in random order, feel free to insert wherever. The actual schedule will be determined by range voting by attendees in April.

**Pull request merged**
