### PR TITLE
Paul Szulc added to lighting talks

### PR DESCRIPTION
**Pull request by EncodePanda**
I did not know whether to put it under 'lightning talks' or  'presentations' -  i was told it will take 25min slot, thus I've choose lightning. If that should be under 'presentations' please let me know - i will rearrange that

### CODE REVIEW

**Comment by jdegoes** [comment]
The lightning talks are 5 mins. :) Please move to presentations. Is 25 minutes enough time to do the topic justice?

**Comment by EncodePanda** [comment]
It is designed as 30 min talk,  I should be able to squeeze it to 25min

śr., 15 kwi 2015, 7:08 PM John A. De Goes użytkownik <
notifications@github.com> napisał:

**Comment by jdegoes** [comment]
OK, please move over to the presentations section and I'll merge it in. Thanks!

**Comment by jdegoes** [comment]
Hi Pawel, can you add your speaker bio and pic, too?

**Comment by jdegoes** [comment]
@rabbitonweb ^^^ Bump :smile:

**Comment by EncodePanda** [comment]
sorry for delays, info added

**Pull request merged**
